---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  name: global-application-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - global
...