---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 10Gi
    thanosRuler:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
...