---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment-helm
  namespace: hello-world
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      deployment: hello-helm
  template:
    metadata:
      labels:
        deployment: hello-helm
    spec:
      containers:
      - name: the-container-helm
        image: monopole/hello:1
        command: ["/hello",
                  "--port=8080",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: the-map-helm
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: the-map-helm
              key: enableRisky
...