---
kind: Service
apiVersion: v1
metadata:
  name: the-service-helm
  namespace: hello-world
spec:
  selector:
    deployment: hello
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8667
    targetPort: 8080
...