---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-cluster-monitoring
spec:
  project: acm
  source:
    repoURL: https://github.com/adonisgarciac/acm-gitops-modes.git
    targetRevision: main
    path: 'monitoring'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: false
      prune: false
    syncOptions: []
...
