---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: globalconfig-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: global-application-placement
              requeueAfterSeconds: 180
          - git:
              repoURL: https://github.com/adonisgarciac/gitops-pull-mode.git
              revision: main
              directories:
              - path: push-mode/base/monitoring/
              - path: push-mode/overlay/{{cluster}}/monitoring/
  template:
    metadata:
      name: test
    spec:
      project: acm
      source:
        repoURL: https://github.com/adonisgarciac/gitops-pull-mode.git
        targetRevision: main
        path: push-mode/base/monitoring/
      destination:
        namespace: openshift-monitoring
        server: '{{server}}'
      syncPolicy:
        automated:
          selfHeal: false
          prune: false
        syncOptions: []
...