---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pull-kustomize-globalconfig-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: managedcluster-application-placement
          - git:
              repoURL: https://github.com/adonisgarciac/gitops-pull-mode.git
              revision: main
              directories:
              - path: helloworld-kustomize/overlay/{{clusterName}}
  template:
    metadata:
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: '{{clusterName}}'
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
      name: '{{clusterName}}-{{path[0]}}'
    spec:
      project: acm
      source:
        repoURL: https://github.com/adonisgarciac/gitops-pull-mode.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          selfHeal: false
          prune: false
        syncOptions: []
...