---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: push-globalconfig-applicationset-helm
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: global-application-placement
          - git:
              repoURL: https://github.com/adonisgarciac/gitops-pull-mode.git
              revision: main
              directories:
              - path: helloworld-helm
  template:
    metadata:
      name: '{{clusterName}}-{{path[0]}}'
    spec:
      project: acm
      source:
        repoURL: https://github.com/adonisgarciac/gitops-pull-mode.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
            - values_{{clusterName}}.yaml
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          selfHeal: false
          prune: false
        syncOptions: []
...